version: '3.9'

networks:
  huihui-subscribe-man:
    driver: bridge

services:
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data
  #   networks:
  #     - huihui-mahjong

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:${HUIHUI_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${HUIHUI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HUIHUI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HUIHUI_POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - huihui-subscribe-man

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${HUIUHI_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${HUIUHI_PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - huihui-subscribe-man
